server:
  port: 8062
#  应用名称（nacos会将该名称当做服务名称）
spring:
  application:
    name: order-openFeign-sentinel
  cloud:
    nacos:
      discovery:
#        nacos服务地址
        server-addr: 192.168.88.128:8848
#        用户名
        username: nacos
#        密码
        password: nacos
#        命名空间
        namespace: public
    sentinel:
      transport:
        dashboard: 192.168.88.128:8858 #sentinel服务地址
      web-context-unify: false  #默认将调用链路收敛，收敛的话会导致链路流控失效
feign:
  sentinel:
#    openfeign整合sentinel
    enabled: true
