server:
  port: 8061
spring:
  application:
    name: order-sentinel
  cloud:
    sentinel:
      transport:
        dashboard: 192.168.88.128:8858
      web-context-unify: false  #默认将调用链路收敛，收敛的话会导致链路流控失效
      datasource:
        flow-rule: #这个flow-rule是可以自定义的
          nacos:
            server-addr: 192.168.88.128:8848
            username: nacos
            password: nacos
            dataId: order-sentinel-flow-rule
            rule-type:  flow

