server:
  port: 8030
#  应用名称（nacos会将该名称当做服务名称）
spring:
  application:
    name: order-service-ribbon
  cloud:
    nacos:
      discovery:
#        以下信息使用的都是默认值
#        nacos服务地址
        server-addr: 192.168.88.128:8848
#        用户名
        username: nacos
#        密码
        password: nacos
#        命名空间
        namespace: public

  main:
    allow-bean-definition-overriding: true

stock-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule
