server:
  port: 8021
#  应用名称（nacos会将该名称当做服务名称）
spring:
  application:
    name: stock-service
  cloud:
    nacos:
      discovery:
#        nacos服务地址
        server-addr: 192.168.88.128:8848
#        用户名
        username: nacos
#        密码
        password: nacos
#        命名空间
        namespace: public #相同特征的服务进行归类分组管理

#        weight:  权重，通常要结合 安装 权重的负载均衡策略，权重越高，分配的流量越大
#        group:  默认DEFAULT_GROUP 更细的相同特征的服务进行归类分组管理
#        service:  默认读取${spring.application.name},也可以通过该选项配置
#        ephemeral: false #        永久实例，哪怕服务宕机了，也不会删除实例   默认是临时实例true