server:
  port: 8040
#  应用名称（nacos会将该名称当做服务名称）
spring:
  application:
    name: order-loadBalancer
  cloud:
    nacos:
      discovery:
#        nacos服务地址
        server-addr: 192.168.88.128:8848
#        用户名
        username: nacos
#        密码
        password: nacos
#        命名空间
        namespace: public

#        关闭Spring Cloud中默认的负载均衡器ribbon
    loadbalancer:
      ribbon:
        enabled: false

  main:
    allow-bean-definition-overriding: true

