server:
  port: 8060
spring:
  profiles:
    active: dev
#    在配置中心中，可以通过profile进行设置
#    只有默认的配置文件才能结合profile进行使用
#    对应的Data ID是  {服务名}-${profiles.active}.{后缀名}
#    profile的后缀必须跟随默认配置文件的格式

  application:
    # 会自动根据服务名拉取Data ID对应的配置文件
    # 如果Data ID与服务名不一致，就需要手动配置Data ID
    # 跟服务名相同的Data ID的配置文件，称之为默认的配置文件
    # 除了默认的配置文件，其他的配置文件必须写上后缀
    name: com.example.config